### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by davad** [KyleAMathews/Journal#1]
Deploying to heroku I got this error:

```
   Using Node.js version: 0.6.20
   Using npm version: 1.0.106
   ...
   npm ERR! Error: No compatible version found: appcache-brunch
   npm ERR! No valid targets found.
   npm ERR! Perhaps not compatible with your version of node?
```

I'm guessing appcache-brunch is incompatible with the Node.js version declared in packages.json.

**Comment by KyleAMathews** [comment]
Yeah -- `appcache-brunch` requires Node.js 0.8.x -- which Heroku doesn't provide by default - https://devcenter.heroku.com/articles/nodejs-versions

I'm filling out the README.md right now so I'll mention this.

**Comment by davad** [comment]
In packages.json it calls for node version ~0.6. I changed that to ~0.8 for node and added an entry for the npm version. https://github.com/davad/Journal/blob/master/package.json

**Comment by KyleAMathews** [comment]
Ooops, missed that :) Could you make a pull request?
