### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by davad** [KyleAMathews/Journal#3]
In running `compass compile`, I found the following missing dependencies:
- susy
- compass-normalize
- sassy-buttons

After installing these dependencies, it complained that the mixin `animation-support` was not defined (line 322 and lines 351 to 362).

**Comment by davad** [comment]
It also complained about the mixin `keyframes`.

**Comment by KyleAMathews** [comment]
Look better? https://github.com/KyleAMathews/Journal/blob/master/README.md
