### ISSUE TITLE
Geolocation problem

### ISSUE THREAD

**Issue by davad** [KyleAMathews/Journal#5]
When I try to save a post on my phone using Chrome, it fails while trying to get gelocation data (see attached image).

![Screenshot from 2013-03-01 18:45:14](https://f.cloud.github.com/assets/190387/212252/57bd6af2-82db-11e2-8c00-4c5d5a07ee41.png)

**Comment by KyleAMathews** [comment]
I think I'm running into the same problem. I'll roll out a fix next time I work on this.

**Comment by KyleAMathews** [comment]
Fixed w/ https://github.com/KyleAMathews/Journal/commit/aa9a2877c88c149eba28cc23d69c90f4ac338606
